### ISSUE TITLE
Make Java Solution & Documentation for #4a

### ISSUE THREAD

**Issue by Ank221199** [Ank221199/Code-Forces-ProblemSet#51]

**Comment by Ank221199** [comment]
# Solution 
The Solution provided should be passing all the test cases from Codeforces.

# Documentation
The document provided should explain the proper working of the code and demonstrate how to crack the problem given with suitable examples.

**Comment by agkeshav** [comment]
Please assign me this issue I can do this well

**Comment by Ank221199** [comment]
#62
